dist: trusty
language: python
python: 3.8
os: linux

services:
  - docker

install: make bootstrap

script: make lint test integration_tests

before_deploy:
  - git stash --all
  - make set_version
deploy:
  provider: pypi
  username: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  cleanup: false
  on:
    branch: master
    tags: true
