# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent/spanAgent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from .. import span_pb2 as span__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent/spanAgent.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\"com.expedia.open.tracing.agent.apiP\001Z\010haystack'),
  serialized_pb=_b('\n\x15\x61gent/spanAgent.proto\x1a\nspan.proto\"\x95\x01\n\x0e\x44ispatchResult\x12(\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1a.DispatchResult.ResultCode\x12\x15\n\rerror_message\x18\x02 \x01(\t\"B\n\nResultCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x11\n\rUNKNOWN_ERROR\x10\x01\x12\x14\n\x10RATE_LIMIT_ERROR\x10\x02\x32/\n\tSpanAgent\x12\"\n\x08\x64ispatch\x12\x05.Span\x1a\x0f.DispatchResultB0\n\"com.expedia.open.tracing.agent.apiP\x01Z\x08haystackb\x06proto3')
  ,
  dependencies=[span__pb2.DESCRIPTOR,])



_DISPATCHRESULT_RESULTCODE = _descriptor.EnumDescriptor(
  name='ResultCode',
  full_name='DispatchResult.ResultCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ERROR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RATE_LIMIT_ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=121,
  serialized_end=187,
)
_sym_db.RegisterEnumDescriptor(_DISPATCHRESULT_RESULTCODE)


_DISPATCHRESULT = _descriptor.Descriptor(
  name='DispatchResult',
  full_name='DispatchResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='DispatchResult.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='DispatchResult.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DISPATCHRESULT_RESULTCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=187,
)

_DISPATCHRESULT.fields_by_name['code'].enum_type = _DISPATCHRESULT_RESULTCODE
_DISPATCHRESULT_RESULTCODE.containing_type = _DISPATCHRESULT
DESCRIPTOR.message_types_by_name['DispatchResult'] = _DISPATCHRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DispatchResult = _reflection.GeneratedProtocolMessageType('DispatchResult', (_message.Message,), dict(
  DESCRIPTOR = _DISPATCHRESULT,
  __module__ = 'agent.spanAgent_pb2'
  # @@protoc_insertion_point(class_scope:DispatchResult)
  ))
_sym_db.RegisterMessage(DispatchResult)


DESCRIPTOR._options = None

_SPANAGENT = _descriptor.ServiceDescriptor(
  name='SpanAgent',
  full_name='SpanAgent',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=189,
  serialized_end=236,
  methods=[
  _descriptor.MethodDescriptor(
    name='dispatch',
    full_name='SpanAgent.dispatch',
    index=0,
    containing_service=None,
    input_type=span__pb2._SPAN,
    output_type=_DISPATCHRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPANAGENT)

DESCRIPTOR.services_by_name['SpanAgent'] = _SPANAGENT

# @@protoc_insertion_point(module_scope)
